const DefaultJobData = {
  company: "N/A",
  title: "N/A",
  salary: "N/A",
  location: "N/A",
  type: "N/A",
  description: "N/A",
  requirements: [],
  skills: [],
  experience: "N/A",
  education: "N/A",
  benefits: [],
  keywords: [],
  department: "N/A",
  reportingTo: "N/A",
  workModel: "N/A",
  applicationDeadline: "N/A",
  applicationUrl: "N/A",
  contactEmail: "N/A",
  jobId: "N/A",
  postedDate: "N/A",
  industryType: "N/A",
  companySize: "N/A",
  workSchedule: "N/A",
  travelRequired: "N/A",
  securityClearance: "N/A",
  visaSponsorship: "N/A",
};

export default DefaultJobData;
